name: cd-env
channels:
  - defaults
dependencies:
  - python=3.6.8
  - networkx=2.2
  - numpy=1.16.3
  - pandas=0.23.4
  - scikit-learn=0.20.3
  - seaborn=0.9.0
  - scipy=1.2.0
  - pyyaml
  - pytz
  - psutil
  - pip
  - pip:
    - rpy2==3.1.0
    - tensorflow==1.13.1
    - matplotlib==3.1.3
    - xxhash==1.3.0
    - multiprocess==0.70.7
    - pygraphviz==1.5
    - notebook==5.7.13 # or try 4.4.1 otherwise.
    - ipykernel==5.1.2







